#!/usr/bin/env bash

pprint() {
    if [[ "$tput_support" == "y" ]]; then
        echo "$1" > "$locsync"
    else
        printf "%s\n" "$1"
    fi
}


clean_draw() {
    echo "" > "$locsync"
    sleep 0.2
    kill "$(jobs -p)" 2>/dev/null
    rm "$locsync" &>/dev/null
    printf "\e[?25h\n"
    return 0
}


draw_bar() {
    printf "\e[?25l"
    local locsync="$1"
    while true; do
        while [[ -z "$(cat "$locsync")" ]]; do sleep 1; done
        for status in "|" "/" "-" "\\"; do
            printf "\e[2K\r[%s] %s" "$status" "$(cat "$locsync")"
            sleep 0.1
        done
    done
}


print_help() {
    printf "\033[1m\033[4mALD\033[24m\tApply & manage container image based os deployments\033[0m\n\n"
    printf "\033[1mUsage:\033[0m\tald SUBCOMMAND [OPTIONS]... [ARGUMENTS]...\n\n"
    printf "\033[1mSubcommands:\033[0m\n"
    printf "\thelp\t\tPrint this menu\n"
    printf "\tstatus\t\tPrint active and available deployments and their versions\n"
    printf "\tpull\t\tPull the newest version of the upstream container image, if a new version is available\n"
    printf "\tbuild\t\tBuild a Containerfile in %s\n" "${ALD_PATH:?}"
    printf "\tswap\t\tReplace the currently active deployment with another specified, available one\n"
    printf "\trm\t\tRemove a specified, available deployment\n"
    printf "\tgc\t\tRemove old deployments until only n=KEEP_DEPS remain\n"

    printf "\tdep\t\tDeploy new versions\n"
    printf "\t\t\tOptions:\n"
    printf "\t\t\t\t-u\tPull newest image before deploying\n"
    printf "\t\t\t\t\t(Same as \`ald pull\`)\n"
    printf "\t\t\t\t-b\tBuild the local Containerfile before deploying\n"
    printf "\t\t\t\t\tCurrently required for the local image to be used\n"
    printf "\t\t\t\t\t(Same as \`ald build\`)\n"
    printf "\t\t\t\t-s\tSwap to the new deployment immediately after building\n"
    printf "\t\t\t\t\t(Same as \`ald swap DEPLOYMENT\`)\n"
    printf "\t\t\t\t-g\tTrigger gc after deploying\n"
    printf "\t\t\t\t\t(Same as \`ald gc\`)\n"
    printf "\t\t\t\t-z\tRelabel files according to the new deployment's selinux policy\n"

    printf "\tinit\t\tInitialise ALD on a system\n"
    printf "\t\t\tOptions:\n"
    printf "\t\t\t\t-b\tBuild the local Containerfile before initialising\n"
    printf "\t\t\t\t\tCurrently required for the local image to be used\n"
    printf "\t\t\t\t\t(Same as \`ald build\`)\n"
    printf "\t\t\t\t-z\tRelabel files according to the new deployment's selinux policy\n"
    printf "\t\t\t\t--ex\tUse a customised %s,\n\t\t\t\t\tit will be used instead of an automatically generated entry\n" "${ALD_PATH:?}/boot.conf.ex"

    printf "\tbootloader_update\tUpdate the system's bootloader\n"
    printf "\t\t\tOptions (one is required):\n"
    printf "\t\t\t\t--fg\tUpdate grub on fedora x86_64 systems\n"
}


print_status() {
    read -ra available_deployments <<< "$(find "${ALD_PATH:?}" -maxdepth 1 -type d -name "[0-9]*" | awk -F'/' '{print $NF}' | sort -nr | tr "\n" " ")"
    depl_version="$(grep ^VERSION= < "/usr/lib/os-release" | cut -d'=' -f2)"
    depl_name="$(grep ^NAME= < "/usr/lib/os-release" | cut -d'=' -f2)"
    printf "\033[1mCurrently active deployment:\033[0m\n\n"
    printf "\t\033[1m\033[4m%s\033[0m\t\u2500\u2500\u2500\tName: %s\n" "$(cat "${ALD_PATH:?}/current")" "$depl_name"
    printf "\t\t\tVersion: %s\n" "$depl_version"
    printf "\t\t\tKernel: \"%s\"\n\n\n" "$(find "/usr/lib/modules" -maxdepth 1 -type d | sort | tail -n1 | awk -F'/' '{ print $NF }')"
    printf "\033[1mOther available deployments:\033[0m\n\n"
    for depl in "${available_deployments[@]}"; do
        depl_version="$(grep ^VERSION= < "${ALD_PATH:?}/$depl/usr/lib/os-release" | cut -d'=' -f2)"
        depl_name="$(grep ^NAME= < "${ALD_PATH:?}/$depl/usr/lib/os-release" | cut -d'=' -f2)"
        printf "\t\033[1m%s\033[0m\t\u2500\u2500\u2500\tName: %s\n" "$depl" "$depl_name"
        printf "\t\t\tVersion: %s\n" "$depl_version"
        printf "\t\t\tKernel: \"%s\"\n\n" "$(find "${ALD_PATH:?}/$depl/usr/lib/modules" -maxdepth 1 -type d | sort | tail -n1 | awk -F'/' '{ print $NF }')"
    done
}


fail_ex() {
    printf "\n\033[31;1mCritical Failure!\033[0m\n%s\n\n" "$2"
    rm "$locsync" &>/dev/null
    if [[ ! "$(cat "${ALD_PATH:?}/current")" == "$1" && ! "$1" == "-1" ]]; then
        pprint "Attempting cleanup..."
        podman rm ald-tmp &>/dev/null
        podman rm ald-utils &>/dev/null
        podman rm ald-boot &>/dev/null
        rm -rf "${ALD_PATH:?}/${1:?}"
        chattr -f -i "${ALD_PATH:?}/init/$1.sh"
        rm -rf "${ALD_PATH:?}/init/${1:?}.sh"
        rm -rf "${BOOT_PATH:?}/${1:?}"
        rm -rf "${BOOT_PATH:?}/loader/entries/${1:?}.conf"
    fi
    mountpoint /usr &>/dev/null || (mount -o bind,ro /usr /usr && mount -o bind,rw /usr/local /usr/local)
    mountpoint "${ALD_PATH:?}" &>/dev/null || mount -o bind,ro "${ALD_PATH:?}" "${ALD_PATH:?}"
    exit 1
}


pull_image() {
    pprint "Checking for updates..."
    installed_image="$(podman inspect --format '{{.Digest}}' "$SOURCE_IMAGE" 2>/dev/null)"
    remote_image="$(skopeo inspect --format '{{.Digest}}' "docker://$SOURCE_IMAGE" 2>/dev/null)"
    if [[ "$installed_image" == "$remote_image" ]]; then
        printf "Latest image already pulled.\nIf the invoked command was \`ald dep\` omit \"-u\" to create a new deployment anyways.\n"
        exit 0
    else
        pprint "Pulling $SOURCE_IMAGE..."
        if [[ "$tput_support" == "y" ]]; then echo "" > "$locsync" && tput smcup; fi
        podman pull "$SOURCE_IMAGE" || fail_ex "-1" "Pulling image failed."
        if [[ "$tput_support" == "y" ]]; then tput rmcup; fi
    fi
}


build_image() {
    pprint "Building local image..."
    if [[ "$tput_support" == "y" ]]; then echo "" > "$locsync" && tput smcup; fi
    podman build --build-arg=SOURCE_IMAGE="$SOURCE_IMAGE" -t "$LOCAL_TAG" "${CONFIG_PATH:?}" || fail_ex "-1" "Building image failed."
    if [[ "$tput_support" == "y" ]]; then pprint "Finished building image..." && tput rmcup; fi
}


setup_dep() {
    shift
    if [[ "$*" == "-"*"u"* ]]; then pull_image; fi
    if [[ "$*" == "-"*"b"* ]]; then build_image && sleep 1 && SOURCE_IMAGE="$LOCAL_TAG"; fi

    pprint "Retrieving vars..."
    current_id="$(cat "${ALD_PATH:?}/current")"
    max_id="$(find "${ALD_PATH:?}" -maxdepth 1 -type d -name "[0-9]*" | awk -F'/' '{print $NF}' | sort -n | tail -n1)"
    max_id="$(echo "$current_id" "$max_id" | tr " " "\n" | sort -n | tail -n1)"
    next_id="$((max_id+1))"

    trap 'fail_ex $next_id "Failed to create deployment."' INT TERM

    pprint "Unlocking image storage..."
    mountpoint "${ALD_PATH:?}" &>/dev/null && umount -f "${ALD_PATH:?}"

    pprint "Creating directories..."
    mkdir -p "${ALD_PATH:?}/$next_id/usr" || fail_ex "$next_id" "Couldn't create deployment root."
    mkdir -p "${BOOT_PATH:?}/$next_id" || fail_ex "$next_id" "Couldn't create deployment boot directory."

    pprint "Syncing image root to fs..."
    podman create --name ald-tmp "$SOURCE_IMAGE" &>/dev/null || fail_ex "$next_id" "Couldn't sync files."
    MOUNTC="$(podman mount ald-tmp)"
    mkdir -p "${ALD_PATH:?}/image"
    rsync -aHlcx --delete "$MOUNTC"/{usr,etc} "${ALD_PATH:?}/image" || fail_ex "$next_id" "Couldn't sync files."
    rsync -aHlx "$MOUNTC"/usr/etc/ "${ALD_PATH:?}/image/etc/" &>/dev/null
    podman unmount ald-tmp &>/dev/null || printf "Temporary container still mounted!\n"

    pprint "Creating deployment $next_id..."
    rsync -aHlx --link-dest="../../image/usr/" "${ALD_PATH:?}/image/usr/" "${ALD_PATH:?}/$next_id/usr/" || fail_ex "$next_id" "Couldn't sync files."
    rsync -aHlx "${ALD_PATH:?}/image/etc" "${ALD_PATH:?}/$next_id" || fail_ex "$next_id" "Couldn't sync files."

    pprint "Syncing system configuration..."
    if [[ "$STATE" == "drop" ]]; then
        reset_state "$next_id"
    else
        rsync -alHx /etc "${ALD_PATH:?}/$next_id" || fail_ex "$next_id" "Couldn't place system config."
    fi
    podman cp ald-tmp:/etc/passwd "${ALD_PATH:?}" || fail_ex "$next_id" "Couldn't place system config."
    podman cp ald-tmp:/etc/shadow "${ALD_PATH:?}" || fail_ex "$next_id" "Couldn't place system config."

    sort /etc/passwd "${ALD_PATH:?}/passwd" | awk -F':' '!a[$1]++' > "$ALD_PATH/$next_id/etc/passwd" || fail_ex "$next_id" "Couldn't place system config."
    sort /etc/shadow "${ALD_PATH:?}/shadow" | awk -F':' '!a[$1]++' > "$ALD_PATH/$next_id/etc/shadow" || fail_ex "$next_id" "Couldn't place system config."
    rm "${ALD_PATH:?}"/{passwd,shadow} || fail_ex "$next_id" "Couldn't place system config."

    podman rm ald-tmp &>/dev/null || fail_ex "$next_id" "Couldn't remove temporary container."

    new_kernel="$(find "${ALD_PATH:?}/$next_id/usr/lib/modules" -name vmlinuz | sort | tail -n1)" || fail_ex "$next_id" "Couldn't place new kernel."
    new_init="$(find "${ALD_PATH:?}/$next_id/usr/lib/modules" -name initramfs.img | sort | tail -n1)" || fail_ex "$next_id" "Couldn't place new initramfs."
    cp -rfa "$new_kernel" "${BOOT_PATH:?}/$next_id" || fail_ex "$next_id" "Couldn't place new kernel."
    cp -rfa "$new_init" "${BOOT_PATH:?}/$next_id" || fail_ex "$next_id" "Couldn't place new initramfs."

    deduplicate_boot_files
    if [[ "$*" == "-"*"z"* ]]; then apply_selinux_policy "$next_id"; fi

    pprint "Preparing boot entry..."
    cp -rfa "${ALD_PATH:?}/boot.conf" "${BOOT_PATH:?}/loader/entries/$next_id.conf" || fail_ex "$next_id" "Couldn't place boot config."
    sed -i "s@INSERT_DEPLOYMENT@$next_id@g" "${BOOT_PATH:?}/loader/entries/$next_id.conf" || fail_ex "$next_id" "Placing template files for $ID failed."

    if [[ "$*" == "-"*"s"* ]]; then swap_deployment "$next_id"; fi
    if [[ "$*" == "-"*"g"* ]]; then rm_deps; fi

    pprint "Deployment $next_id installed!"

    if [[ -f "${ALD_PATH:?}/ald" ]]; then rm "${ALD_PATH:?}/ald"; fi

    pprint "Locking image storage..."
    mountpoint "${ALD_PATH:?}" &>/dev/null || mount -o bind,ro "${ALD_PATH:?}" "${ALD_PATH:?}"
}


show_updates() {
    rpm --version &>/dev/null || fail_ex "-1" "Currently only rpm-based systems are supported."
    if [[ "$(find "${ALD_PATH:?}" -maxdepth 1 -type d -printf "%P ")" != *"$1"* && "$1" != "$(cat "${ALD_PATH:?}"/current)" ]]; then
        fail_ex "-1" "No such deployment: $1."
    elif [[ "$(find "${ALD_PATH:?}" -maxdepth 1 -type d -printf "%P ")" != *"$2"* && "$2" != "$(cat "${ALD_PATH:?}"/current)" ]]; then
        fail_ex "-1" "No such deployment: $2."
    fi
    FALLBACK="$(find "${ALD_PATH:?}" -maxdepth 1 -type d -name "[0-9]*" | awk -F'/' '{print $NF}' | sort -n | tail -n1)"
    if [[ -n "$1" && "$1" != "$(cat "${ALD_PATH:?}/current")" ]]; then OLD_DEP="${ALD_PATH:?}/$1"; else OLD_DEP="${ALD_PATH:?}/$FALLBACK"; fi
    if [[ -n "$2" && "$2" != "$(cat "${ALD_PATH:?}/current")" ]]; then NEW_DEP="${ALD_PATH:?}/$2"; else NEW_DEP="/"; fi
    printf "Comparing %s and %s:\n" "$OLD_DEP" "$NEW_DEP"
    rpm -qa --root="$OLD_DEP" | sort > "$HOME/.old" || (rm "$HOME/.old" && fail_ex "-1" "Couldn't retrieve packages from $OLD_DEP.")
    rpm -qa --root="$NEW_DEP" | sort > "$HOME/.new" || (rm "$HOME/"{.old,.new} && fail_ex "-1" "Couldn't retrieve packages from $NEW_DEP.")
    diff -y "$HOME/.old" "$HOME/.new" | grep "|\|>\|<" || pprint "There doesn't seem to be a difference bewteen $OLD_DEP and $NEW_DEP."
    rm "$HOME/"{.old,.new} || printf "Failed to delete temporary files.\n"
}


swap_deployment() {
    PREFIX=""
    if [[ -f "/etc/initrd-release" ]]; then PREFIX="/sysroot"; fi
    if [[ "$(find "${ALD_PATH:?}" -maxdepth 1 -type d -printf "%P ")" != *"$1"* || -z $1 ]]; then
        fail_ex "-1" "Deployment $1 doesn't exist or can't be swapped to."
    fi
    pprint "Unlocking image storage..."
    mountpoint "${ALD_PATH:?}" &>/dev/null && umount -f "${ALD_PATH:?}" &>/dev/null

    pprint "Replacing deployment $(cat "${ALD_PATH:?}/current") with $1."
    chattr -i "$PREFIX/" || if [[ ! -f "/etc/initrd-release" ]]; then printf "Couldn't unlock /.\n"; fi
    (mountpoint "$PREFIX/usr" &>/dev/null && umount -Rfl "$PREFIX/usr") ||
        if [[ ! -f "/etc/initrd-release" ]]; then printf "Couldn't temporarily remove /usr bind mount.\n"; fi

    exch "$PREFIX/usr" "${ALD_PATH:?}/$1/usr" || fail_ex "-1" "Couldn't atomically switch deployments."  
    exch "$PREFIX/etc" "${ALD_PATH:?}/$1/etc" || printf "Couldn't atomically switch system config, system might be instable."

    mount -o bind,ro "$PREFIX/usr" "$PREFIX/usr" || printf "Restoring /usr bind mount failed, fs is rw."
    mount -o bind,rw "$PREFIX/usr/local" "$PREFIX/usr/local" || printf "Restoring /usr bind mount failed, fs is rw."
    chattr +i "$PREFIX/" || printf "Couldn't lock /.\n"

    swapped_dep="$(cat "${ALD_PATH:?}/current")"
    echo "$1" > "${ALD_PATH:?}/current" || printf "Saving new deployment failed, naming out of sync."
    mv "${ALD_PATH:?}/$1" "${ALD_PATH:?}/$swapped_dep" || printf "Renaming old deployment failed, naming out of sync."

    pprint "Locking image storage..."
    if [[ ! -f "/etc/initrd-release" ]]; then
        (mountpoint "${ALD_PATH:?}/$swapped_dep/usr/local" &>/dev/null && umount -Rfl "${ALD_PATH:?}/$swapped_dep/usr/local") ||
            printf "/usr/local might still be mounted to old deployment"
    fi
    mountpoint "${ALD_PATH:?}" &>/dev/null || mount -o bind,ro "${ALD_PATH:?}" "${ALD_PATH:?}"
}


reset_state() {
    pprint "Syncing absolutely required config..."
    cp -rfa --parents /etc/fstab /etc/crypttab /etc/locale.conf /etc/localtime /etc/adjtime \
        /etc/sudoers.d /etc/group /etc/gshadow /etc/subgid /etc/subuid \
        /etc/NetworkManager/system-connections /etc/vconsole.conf /etc/pki \
        /etc/firewalld /etc/environment /etc/hostname \
        /etc/X11/xorg.conf.d/00-keyboard.conf /etc/sudoers /etc/ald \
        "${ALD_PATH:?}/$1/" || fail_ex "$1" "Resetting /etc failed."
}


apply_selinux_policy() {
    pprint "Relabeling deployment $1..."
    restorecon -RF "${BOOT_PATH:?}"
    setfiles -r "${ALD_PATH:?}/$1" "${ALD_PATH:?}/$1/etc/selinux/targeted/contexts/files/file_contexts" "${ALD_PATH:?}/$1" &>/dev/null
}


deduplicate_boot_files() {
    pprint "Deduplicating inactive deployments..."
    read -ra available_boot_files <<< "$(find "${BOOT_PATH:?}" -maxdepth 1 -type d -name "[0-9]*" -not -path "${BOOT_PATH:?}/$(cat "${ALD_PATH:?}"/current)" | tr "\n" " ")"
    if [[ "$tput_support" == "y" ]]; then echo "" > "$locsync" && tput smcup; fi
    hardlink -tXOv -s1 "${available_boot_files[@]}"
    if [[ "$tput_support" == "y" ]]; then tput rmcup; fi
    echo "" > "$locsync"
}


rm_dep() {
    pprint "Unlocking image storage..."
    mountpoint "${ALD_PATH:?}" &>/dev/null && umount -Rf "${ALD_PATH:?}"
    pprint "Removing deployment $1..."
    if [[ "$(find "${ALD_PATH:?}" -maxdepth 1 -type d -printf "%P ")" != *"$1"* || -z $1 ]]; then
        fail_ex "-1" "Deployment $1 doesn't exist or isn't removable."
    fi
    podman rm ald-tmp &>/dev/null
    rm -rf "${ALD_PATH:?}/$1" || printf "Removing %s failed, manual intervention might be necessary.\n" "$ALD_PATH/$1"
    rm -rf "${BOOT_PATH:?}/$1" || printf "Removing %s failed, manual intervention might be necessary.\n" "$BOOT_PATH/$1"
    rm -rf "${BOOT_PATH:?}/loader/entries/$1.conf" || printf "Removing %s failed, manual intervention might be necessary.\n" "$BOOT_PATH/loader/entries/$1.conf"
    mountpoint /usr &>/dev/null || (mount -o bind,ro /usr /usr && mount -o bind,rw /usr/local /usr/local)
    pprint "Locking image storage..."
    mountpoint "${ALD_PATH:?}" &>/dev/null || mount -o bind,ro "${ALD_PATH:?}" "${ALD_PATH:?}"
}


rm_deps() {
    while [[ "$(find "${ALD_PATH:?}" -maxdepth 1 -type d -name "[0-9]*" | awk -F'/' '{print $NF}' | sort -nr | wc -l)" -gt "$((KEEP_DEPS-1))" ]]; do
        rm_dep "$(find "${ALD_PATH:?}" -maxdepth 1 -type d -name "[0-9]*" | awk -F'/' '{print $NF}' | sort -n | head -n1)"
    done
}


init_ald() {
    shift

    ln -s "${ALD_PATH:?}/ald" /usr/bin/ald
    mkdir -p /var/usrlocal
    echo "0" > "${ALD_PATH:?}/current"
    boot_conf="$(find "${BOOT_PATH:?}/loader/entries" | sort | tail -n1)"
    if [[ "$*" == *"--ex"* ]]; then
        mv -f "${ALD_PATH:?}/boot.conf.ex" "${ALD_PATH:?}/boot.conf"
    else
        cp -fa "$boot_conf" "${ALD_PATH:?}/boot.conf" || fail_ex "-1" "Automatic boot entry creation failed."
        (grep -q title "${ALD_PATH:?}/boot.conf" && sed -i "s/^title .*$/title ALD Deployment INSERT_DEPLOYMENT/g" "${ALD_PATH:?}/boot.conf") || fail_ex "-1" "Automatic boot entry creation failed."
        (grep -q version "${ALD_PATH:?}/boot.conf" && sed -i "s/^version .*$/version INSERT_DEPLOYMENT/g" "${ALD_PATH:?}/boot.conf") || fail_ex "-1" "Automatic boot entry creation failed."
        (grep -q linux "${ALD_PATH:?}/boot.conf" && sed -i "s/^linux .*$/linux \/INSERT_DEPLOYMENT\/vmlinuz/g" "${ALD_PATH:?}/boot.conf") || fail_ex "-1" "Automatic boot entry creation failed."
        (grep -q initrd "${ALD_PATH:?}/boot.conf" && sed -i "s/^initrd .*$/initrd \/INSERT_DEPLOYMENT\/initramfs.img/g" "${ALD_PATH:?}/boot.conf") || fail_ex "-1" "Automatic boot entry creation failed."
        (grep -q options "${ALD_PATH:?}/boot.conf" && sed -i "s/^options \(.*\)$/options \1 ald.boot=INSERT_DEPLOYMENT/g" "${ALD_PATH:?}/boot.conf") || fail_ex "-1" "Automatic boot entry creation failed."
    fi

    if [[ "$*" == "-"*"b"* ]]; then build_image && SOURCE_IMAGE="$LOCAL_TAG"; fi
    STATE="drop"
    setup_dep
    if [[ "$*" == "-"*"z"* ]]; then apply_selinux_policy "1"; fi

    pprint "ALD initialised. Rebooting once is needed after initializing/switching image."
}


update_bootloader() {
    if [[ "$*" == *"--fg"* ]]; then
        fedora_grub
    else
        printf "No bootloader seems to be available for this configuration."
    fi
}


fedora_grub() {
    mkdir "${ALD_PATH:?}/tmp-boot"
    cat > "${ALD_PATH:?}/tmp-boot/Containerfile" << EOF
FROM "${SOURCE_IMAGE}"

RUN (sudo dnf5 reinstall -y grub2-efi-x64.x86_64 || sudo dnf5 install -y grub2-efi-x64.x86_64) || (echo "Couldn't install grub!" && exit 1)

RUN (dnf5 reinstall -y shim-x64.x86_64 || sudo dnf5 install -y shim-x64.x86_64) || (echo "Couldn't install shim!" && exit 1)
EOF
    podman build -t localhost/ald-boot "${ALD_PATH:?}/tmp-boot" || fail_ex "-1" "Couldn't create image."
    podman create --name ald-boot localhost/ald-boot &>/dev/null || fail_ex "-1" "Couldn't sync files."

    if [[ "$?" != "0" ]]; then fail_ex "-1" "Failed to fetch bootloader components."; fi
    podman cp ald-boot:/boot/efi/EFI/fedora/shimx64.efi "${EFI_PATH:?}" ||
        fail_ex "-1" "Failed to retrieve bootloader components."
    podman cp ald-boot:/boot/efi/EFI/fedora/grubx64.efi "${EFI_PATH:?}" ||
        fail_ex "-1" "Failed to retrieve bootloader components."
    podman cp ald-boot:/boot/efi/EFI/fedora/mmx64.efi "${EFI_PATH:?}" ||
        fail_ex "-1" "Failed to retrieve bootloader components."
    podman cp ald-boot:/boot/efi/EFI/fedora/BOOTX64.CSV "${EFI_PATH:?}" ||
        fail_ex "-1" "Failed to retrieve bootloader components."
    podman cp ald-boot:/boot/efi/EFI/BOOT/fbx64.efi "${EFI_PATH:?}" ||
        fail_ex "-1" "Failed to retrieve bootloader components."

    pprint "Updating shim..."
    cp "${EFI_PATH:?}/shimx64.efi" "${EFI_PATH:?}/shimx64.efi.bak" ||
        fail_ex "-1" "Failed to prepare bootloader components."
    cp "${EFI_PATH:?}/shimx64.efi" "${EFI_PATH:?}/shimx64.efi.bak.bak" ||
        fail_ex "-1" "Failed to prepare bootloader components."
    exch "${EFI_PATH:?}/shimx64.efi" "${EFI_PATH:?}/EFI/BOOT/BOOTX64.EFI" ||
        fail_ex "-1" "Failed to place bootloader components."
    exch "${EFI_PATH:?}/shimx64.efi.bak" "${EFI_PATH:?}/EFI/fedora/shim.efi" ||
        printf "Failed to place bootloader components.\n"
    exch "${EFI_PATH:?}/shimx64.efi.bak.bak" "${EFI_PATH:?}/EFI/fedora/shimx64.efi" ||
        printf "Failed to place bootloader components.\n"
    rm "${EFI_PATH:?}"/{shimx64.efi,shimx64.efi.bak,shimx64.efi.bak.bak} ||
        printf "Failed to cleanup bootloader components.\n"

    pprint "Updating grub..."
    exch "${EFI_PATH:?}/grubx64.efi" "${EFI_PATH:?}/EFI/fedora/grubx64.efi" ||
        printf "Failed to place bootloader components.\n"
    exch "${EFI_PATH:?}/mmx64.efi" "${EFI_PATH:?}/EFI/fedora/mmx64.efi" ||
        printf "Failed to place bootloader components.\n"
    exch "${EFI_PATH:?}/BOOTX64.CSV" "${EFI_PATH:?}/EFI/fedora/BOOTX64.CSV" ||
        printf "Failed to place bootloader components.\n"
    exch "${EFI_PATH:?}/fbx64.efi" "${EFI_PATH:?}/EFI/BOOT/fbx64.efi" ||
        printf "Failed to place bootloader components.\n"
    rm "${EFI_PATH:?}"/{grubx64.efi,mmx64.efi,BOOTX64.CSV,fbx64.efi} ||
        printf "Failed to cleanup bootloader components.\n"

    podman rm ald-boot &>/dev/null || printf "Failed to remove container ald-boot.\n"
    podman rmi localhost/ald-boot &>/dev/null || printf "Failed to remove image localhost/ald-boot.\n"
    rm -rf "${ALD_PATH:?}/tmp-boot" &>/dev/null
    pprint "Update complete!\n"
}

CONFIG_PATH="${CONFIG_PATH:-/etc/ald}"

source "$CONFIG_PATH/ald-config" &>/dev/null || printf "No config found, using defaults...\n"

SOURCE_IMAGE="${SOURCE_IMAGE:-ghcr.io/nostale3210/timesinkc-main:latest}"
LOCAL_TAG="${LOCAL_TAG:-localhost/ald-root}"
ALD_PATH="${ALD_PATH:-/.ald}"
BOOT_PATH="${BOOT_PATH:-/boot}"
EFI_PATH="${EFI_PATH:-$BOOT_PATH/efi}"
STATE="${ALD_STATE:-keep}"
KEEP_DEPS="${KEEP_DEPS:-4}"

if [[ -f "/etc/initrd-release" ]]; then ALD_PATH="/sysroot$ALD_PATH"; fi

dependency_check() {
    if ! podman --version &>/dev/null || ! rsync --version &>/dev/null; then
        fail_ex "-1" "Dependency check failed! Are podman and rsync installed?"
    fi
}

if (infocmp 2>/dev/null | grep -q smcup) &&
    (infocmp 2>/dev/null | grep -q rmcup); then
    tput_support="y";
else
    tput_support="n";
fi

if systemd-inhibit --help &>/dev/null; then
    sys_inhibit="y";
fi

locsync="/dev/shm/sync$$"
echo "" > "$locsync"
if [[ "$tput_support" == "y" ]]; then
    trap clean_draw 0
    draw_bar "$locsync" &
fi

declare -A -r RUN_CMD=(
    ["build"]="lwPOgI3J0zn6q"
    ["pull"]="SPRjLFOXJvXt7"
    ["swap"]="NJsoQnUMHEfpe"
    ["dep"]="nQ8tKSuA0SJoy"
    ["rm"]="ONK3quF6NgVfC"
    ["gc"]="fM2KhAo1Ko0Pk"
    ["dedupe"]="29UtiseMD5Vji"
    ["self-update"]="QUd1eE2e8cEdn"
    ["bootloader-update"]="QjPZu7VH36P6n"
)

if [[ "$(id -u)" != "0" ]]; then
    case "$1" in
        help)
            print_help
            ;;
        status)
            print_status
            ;;
        diff)
            show_updates "${2-}" "${3-}"
            ;;
        *)
            printf "\033[31;1mThis program needs to be ran as root.\nMore info:\033[0m\n\n"
            print_help
            exit 1
            ;;
    esac
elif [[ "$(id -u)" = "0" && "${!RUN_CMD[*]}" != *"$1"* ]]; then
    case "$1" in
        lwPOgI3J0zn6q)
            dependency_check
            build_image
            ;;
        SPRjLFOXJvXt7)
            dependency_check
            pull_image
            ;;
        NJsoQnUMHEfpe)
            swap_deployment "$2" "${3-}"
            ;;
        nQ8tKSuA0SJoy)
            dependency_check
            setup_dep "$@"
            ;;
        ONK3quF6NgVfC)
            rm_dep "$2"
            ;;
        init)
            dependency_check
            init_ald "$@"
            ;;
        fM2KhAo1Ko0Pk)
            rm_deps
            ;;
        29UtiseMD5Vji)
            deduplicate_boot_files
            ;;
        QUd1eE2e8cEdn)
            dependency_check
            update_ald "${2-}"
            ;;
        QjPZu7VH36P6n)
            dependency_check
            update_bootloader "$@"
            ;;
        diff)
            show_updates "${2-}" "${3-}"
            ;;
        status)
            print_status
            ;;
        help)
            print_help
            ;;
        *)
            printf "\033[31;1mUnrecognized command.\nMore info:\033[0m\n\n"
            print_help
            ;;
    esac
fi

if [[ "${!RUN_CMD[*]}" != *"$1"* ]]; then exit 0; fi

if [[ "$sys_inhibit" == "y" ]]; then
    (systemd-inhibit --list | grep -q ALD) && fail_ex "-1" "ALD is already running.";
fi


for possible_cmd in "${!RUN_CMD[@]}"; do
    if [[ "$1" == "$possible_cmd" ]]; then
        shift
        set -e
        if [[ "$sys_inhibit" == "y" ]]; then
            systemd-inhibit --what="idle:sleep:shutdown" --who="ALD" --why="Modifying/Creating deployments..." \
                ald "${RUN_CMD[$possible_cmd]}" "$@"
        else
            ald "${RUN_CMD[$possible_cmd]}" "$@"
        fi
        exit 0
    fi
done
